/*
 */

package com.gtoretti.drego.utils

/**
 * Constants used throughout the app.
 */
const val DATABASE_NAME = "db"

const val ACCOUNTING_ACCOUNTS_ALL = "Todos"

const val ACCOUNTING_ACCOUNTS_TYPE_RESULT = "Conta de Resultado"
const val ACCOUNTING_ACCOUNTS_TYPE_ASSET = "Conta Patrimonial"

const val ACCOUNTING_ACCOUNTS_LEVEL1_ATIVO = "1. Ativo"
const val ACCOUNTING_ACCOUNTS_LEVEL1_PASSIVO = "2. Passivo"

const val ACCOUNTING_ACCOUNTS_LEVEL2_ATIVO_CIRCULANTE = "1.1. Circulante"
const val ACCOUNTING_ACCOUNTS_LEVEL2_ATIVO_NAO_CIRCULANTE = "1.2. Não-Circulante"
const val ACCOUNTING_ACCOUNTS_LEVEL2_PASSIVO_CIRCULANTE = "2.1. Circulante"
const val ACCOUNTING_ACCOUNTS_LEVEL2_PASSIVO_NAO_CIRCULANTE = "2.2. Não-Circulante"
const val ACCOUNTING_ACCOUNTS_LEVEL2_PASSIVO_PATRIMONIO_LIQUIDO = "2.3. Patrimônio Líquido"

const val ACCOUNTING_ACCOUNTS_LEVEL3_PATRIMONIO_LIQUIDO_CAPITAL_SOCIAL = "2.3.1. Capital Social"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PATRIMONIO_LIQUIDO_RESERVAS_DE_CAPITAL = "2.3.2. Reservas de Capital"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PATRIMONIO_LIQUIDO_AJUSTES_DE_AVALIACAO_PATRIMONIAL = "2.3.3. Ajustes de Avaliação Patrimonial"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PATRIMONIO_LIQUIDO_RESERVAS_DE_LUCROS = "2.3.4. Reservas de Lucros"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PATRIMONIO_LIQUIDO_ACOES_EM_TESOURARIA = "2.3.5. Ações em Tesouraria"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PATRIMONIO_LIQUIDO_PREJUIZOS_ACUMULADOS = "2.3.6. Prejuízos Acumulados"

const val ACCOUNTING_ACCOUNTS_LEVEL3_ATIVO_CIRCULANTE_CAIXA_E_EQUIVALENTES_DE_CAIXA = "1.1.1. Caixa e equivalentes de caixa"
const val ACCOUNTING_ACCOUNTS_LEVEL3_ATIVO_CIRCULANTE_CONTAS_A_RECEBER = "1.1.2. Contas a receber"
const val ACCOUNTING_ACCOUNTS_LEVEL3_ATIVO_CIRCULANTE_ESTOQUES = "1.1.3. Estoques"
const val ACCOUNTING_ACCOUNTS_LEVEL3_ATIVO_CIRCULANTE_DESPESAS_ANTECIPADAS = "1.1.4. Despesas antecipadas"

const val ACCOUNTING_ACCOUNTS_LEVEL3_ATIVO_NAO_CIRCULANTE_ATIVOS_REALIZAVEIS_A_LONGO_PRAZO = "1.2.1. Ativo realizável a longo prazo"
const val ACCOUNTING_ACCOUNTS_LEVEL3_ATIVO_NAO_CIRCULANTE_INVESTIMENTOS_DE_LONGO_PRAZO = "1.2.2. Investimentos de longo prazo"
const val ACCOUNTING_ACCOUNTS_LEVEL3_ATIVO_NAO_CIRCULANTE_IMOBILIZADO = "1.2.3. Ativo imobilizado"
const val ACCOUNTING_ACCOUNTS_LEVEL3_ATIVO_NAO_CIRCULANTE_ATIVOS_INTANGIVEIS = "1.2.4. Ativo intangível"

const val ACCOUNTING_ACCOUNTS_LEVEL3_PASSIVO_CIRCULANTE_FINANCEIRO = "2.1.1. Passivo Circulante Financeiro"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PASSIVO_CIRCULANTE_OPERACIONAL = "2.1.2. Passivo Circulante Operacional"

const val ACCOUNTING_ACCOUNTS_LEVEL3_PASSIVO_NAO_CIRCULANTE_EMPRESTIMOS_E_FINANCIAMENTOS_DE_LONGO_PRAZO = "2.2.1. Empréstimos e financiamentos de longo prazo"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PASSIVO_NAO_CIRCULANTE_DEBENTURES = "2.2.2. Debêntures"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PASSIVO_NAO_CIRCULANTE_OBRIGACOES_FISCAIS_E_TRABALHISTAS_DE_LONGO_PRAZO = "2.2.3. Obrigações fiscais e trabalhistas de longo prazo"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PASSIVO_NAO_CIRCULANTE_PROVISOES_PARA_CONTINGENCIAS = "2.2.4. Provisões para contingências"
const val ACCOUNTING_ACCOUNTS_LEVEL3_PASSIVO_NAO_CIRCULANTE_ARRENDAMENTO_MERCANTIL_FINANCEIRO = "2.2.5. Arrendamento mercantil financeiro (leasing)"

const val ACCOUNTING_ACCOUNTS_TYPE_RESULT_LEVEL1_OPERATING = "Operacional"
const val ACCOUNTING_ACCOUNTS_TYPE_RESULT_LEVEL1_INVESTING = "Investimentos"
const val ACCOUNTING_ACCOUNTS_TYPE_RESULT_LEVEL1_FINANCING = "Financiamentos"

const val CASH_FLOWS_STATEMENT_TYPE_OPERATING = "Fluxo de Caixa Operacional"
const val CASH_FLOWS_STATEMENT_TYPE_INVESTING = "Fluxo de Caixa de Investimentos"
const val CASH_FLOWS_STATEMENT_TYPE_FINANCING = "Fluxo de Caixa de Financiamentos"

const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING = "Categoria Operacional"
const val PERIOD_RESULT_STATEMENT_TYPE_INVESTING = "Categoria Investimentos"
const val PERIOD_RESULT_STATEMENT_TYPE_FINANCING = "Categoria Financiamentos"
const val PERIOD_RESULT_STATEMENT_TYPE_TAX_ON_PROFIT = "Categoria Tributo sobre Lucro"
const val PERIOD_RESULT_STATEMENT_TYPE_OPERATION_DISCONTINUED = "Categoria Operação Descontinuada"


const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING_REVENUE = "Receita"
const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING_COST_OF_SALES = "Custo das Vendas"
const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING_OTHER_OPERATING_REVENUES = "Outras Receitas Operacionais"
const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING_SELLING_EXPENSES = "Despesas de Vendas"
const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING_RESEARCH_AND_DEVELOPMENT_EXPENSES = "Despesas de Pesquisa e Desenvolvimento"
const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING_GENERAL_AND_ADMINISTRATIVE_EXPENSES = "Despesas Gerais e Administrativas"
const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING_GOODWILL_IMPAIRMENT_LOSS = "Perda por Impairment do Goodwill"
const val PERIOD_RESULT_STATEMENT_TYPE_OPERATING_OTHER_OPERATING_EXPENSES = "Outras Despesas Operacionais"

const val PERIOD_RESULT_STATEMENT_TYPE_INVESTING_PROFIT_SHARING_AND_GAINS_FROM_SALE_OF_INTERESTS_IN_ASSOCIATES_AND_JOINT_VENTURES = "Participação no Lucro e Ganhos na Venda de Participação em Coligadas e Joint Ventures"

const val PERIOD_RESULT_STATEMENT_TYPE_FINANCING_INTEREST_EXPENSES_ON_LOANS_AND_LEASE_LIABILITIES = "Despesas de Juros sobre Empréstimos e Passivos de Arrendamento"
const val PERIOD_RESULT_STATEMENT_TYPE_FINANCING_INTEREST_EXPENSES_ON_RETIREMENT_LIABILITIES_AND_PROVISIONS = "Despesas de Juros sobre Passivos de Aposentadoria e Provisões"

const val PERIOD_RESULT_STATEMENT_TYPE_TAX_ON_PROFIT_TAX_EXPENSES_ON_PROFIT = "Despesas de Tributos sobre o Lucro"

const val PERIOD_RESULT_STATEMENT_TYPE_OPERATION_DISCONTINUED_LOSS_FROM_DISCONTINUED_OPERATIONS = "Perda das Operações Descontinuadas"

const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_INITIAL_BALANCES = "Saldos Iniciais"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_CAPITAL_INCREASE = "Aumento de Capital"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_EXPENSES_ON_STOCK_ISSUANCE = "Gastos com Emissão de Ações"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_RECOGNIZED_GRANTED_OPTIONS = "Opções Outorgadas Reconhecidas"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_TREASURY_SHARES_ACQUIRED = "Ações em Tesouraria Adquiridas"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_TREASURY_SHARES_SOLD = "Ações em Tesouraria Vendidas"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_DIVIDENDS = "Dividendos"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_CAPITAL_TRANSACTIONS_WITH_SHAREHOLDERS = "Transações de Capital com os Sócios"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_NET_PROFIT_FOR_PERIOD = "Lucro Líquido do Período"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_FINANCIAL_INSTRUMENTS_ADJUSTMENTS = "Ajustes Instrumentos Financeiros"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_TAXES_ON_FINANCIAL_INSTRUMENT_ADJUSTMENTS = " Tributos s/ Ajustes Instrumentos Financeiros"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_EQUITY_IN_COMPREHENSIVE_INCOME_OF_AFFILIATES = "Equiv. Patrim. s/ Ganhos Abrang. de Coligadas"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_PERIOD_CONVERSION_ADJUSTMENTS = "Ajustes de Conversão do Período"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_TAXES_ON_PERIOD_CONVERSION_ADJUSTMENTS = "Tributos s/ Ajustes de Conversão do Período"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_OTHER_COMPREHENSIVE_RESULTS = "Outros Resultados Abrangentes"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_RECLASSIFICATION_BY_RESULT_FINANCIAL_INSTRUMENT_ADJUSTMENT = "Reclassific. p/ Resultado – Aj. Instrum. Financ."
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_TOTAL_COMPREHENSIVE_RESULT = "Resultado Abrangente Total"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_CREATION_OF_RESERVES = "Constituição de Reservas"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_RESERVATION_REVIEW = "Realização da Reserva de Reavaliação"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_TAXES_ON_REALIZATION_OF_REVALUATION_RESERVE = "Tributos sobre a Realização da Reserva de Reavaliação"
const val EQUITY_CHANGES_STATEMENT_ITEM_TYPE_FINAL_BALANCES = "Saldos Finais"